name = "cat"
version = "0.1.0"

authors = ["VSebastian8"]
description = "Category Theory concepts in Gleam!"
licences = ["Apache-2.0"]
repository = { type = "github", user = "VSebastian8", repo = "cat" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
